/**
 * Branded type for URLs generated by `$href()`.
 *
 * Distinguishes `$href()` output from plain `string` at the type level,
 * while remaining assignable to `string` so existing code is unaffected.
 *
 * @example
 * import type { TypedHref } from "@plainbrew/next-typed-href";
 *
 * type LinkProps = { href: TypedHref };
 *
 * // ✓ $href() の結果はそのまま渡せる
 * <SafeLink href={$href({ route: "/" })} />
 *
 * // ✗ 生の string はコンパイルエラー
 * <SafeLink href="/" />
 */
export type TypedHref = string & { readonly __brand: "TypedHref" };

export type HrefOptions = {
  branded?: boolean;
};

export type HrefReturn<Options extends HrefOptions> = Options["branded"] extends true
  ? TypedHref
  : string;

/**
 * Resolves at the type level whether a given route has dynamic params.
 *
 * Returns `true` when `RouteParamsMap[T]` has any keys, `false` when it is
 * `Record<string, never>` (i.e. a static route with no dynamic segments).
 *
 * @example
 * type Map = { "/": Record<string, never>; "/users/[id]": { id: string } };
 * type A = RouteHasParams<"/", Map>;          // false
 * type B = RouteHasParams<"/users/[id]", Map>; // true
 */
export type RouteHasParams<
  T extends string,
  RouteParamsMap extends Record<string, Record<string, unknown>>,
> = RouteParamsMap[T] extends Record<string, never> ? false : true;

/**
 * Builds the `route` + (optional) `routeParams` shape for a single route.
 *
 * - If the route has dynamic params, the result requires `routeParams`.
 * - If not, only `route` is required.
 *
 * Used by both `defineTypedHref` and `defineTypedHrefWithNuqs` to share the
 * "route identity" portion of their `$href` argument types.
 *
 * @example
 * type Routes = "/" | "/users/[id]";
 * type Map = { "/": Record<string, never>; "/users/[id]": { id: string } };
 *
 * type Home = RouteIdentityFor<"/", Routes, Map>;
 * // => { route: "/" }
 *
 * type User = RouteIdentityFor<"/users/[id]", Routes, Map>;
 * // => { route: "/users/[id]"; routeParams: { id: string } }
 */
export type RouteIdentityFor<
  T extends string,
  Routes extends string,
  RouteParamsMap extends Record<Routes, Record<string, unknown>>,
> = T extends Routes
  ? RouteHasParams<T, RouteParamsMap> extends true
    ? { route: T; routeParams: RouteParamsMap[T] }
    : { route: T }
  : never;
